export const customerInfo = {
  name: 'John',
  lastname: 'Doe',
  email: 'johndoe@example.com',
  idDocument: '1205989641',
  phone: '+123456789',
  dateOfBirth: '1988-08-28',
  gender: '',
  billingAddress: {
    name: 'Juan ',
    lastname: 'Pérez',
    address: 'Calle Verdadera 456',
    province: 'Barcelona',
    canton: 'Sant Martí',
    district: 'El Clot',
    country: 'España',
    phone: '+34 600 123 456',
  },
  shippingAddress: {
    name: 'Juan ',
    lastname: 'Pérez',
    province: 'Valencia',
    canton: 'Ciutat Vella',
    district: 'El Carme',
    country: 'España',
    phone: '+34 600 123 456',
  },
}

export const recentOrders = [
  {
    id: 1,
    orderNumber: crypto.randomUUID(),
    date: '2024-12-01',
    address: 'Calle Comercial 789, Valencia, España',
    total: '€150.00',
    status: 'Enviado',
  },
  {
    id: 2,
    orderNumber: crypto.randomUUID(),
    date: '2024-11-15',
    address: 'Calle Comercial 789, Valencia, España',
    total: '€80.00',
    status: 'Entregado',
  },
  {
    id: 3,
    orderNumber: crypto.randomUUID(),
    date: '2024-10-30',
    address: 'Calle Comercial 789, Valencia, España',
    total: '€200.00',
    status: 'Pendiente',
  },
  {
    id: 4,
    orderNumber: crypto.randomUUID(),
    date: '2024-10-30',
    address: 'Calle Comercial 789, Valencia, España',
    total: '€200.00',
    status: 'Pendiente',
  },
  {
    id: 5,
    orderNumber: crypto.randomUUID(),
    date: '2024-10-30',
    address: 'Calle Comercial 789, Valencia, España',
    total: '€200.00',
    status: 'Pendiente',
  },
]
